on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    env:
      username_param: '${{ secrets.DB_USERNAME }}'
      password_param: '${{ secrets.DB_PASSWORD }}'
      hostname_param: '${{ secrets.DB_HOSTNAME }}'
      port_param: '${{ secrets.DB_PORT }}'
      database_param: '${{ secrets.DB_DATABASE }}'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        buildArgs: db_username=${{env.username_param}}, db_password=${{env.password_param}}, db_hostname=${{env.hostname_param}}, db_port=${{env.port_param}}, db_database=${{env.database_param}}
        context: .
        push: true
        tags: cutibo29/charging-station:latest, cutibo29/charging-station:${{github.run_number}}
